-
  name: Install Nginx and Docker
  hosts: your_ec2_instance
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
